# Generated by Django 5.2 on 2025-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_cartitem_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='total_items',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=1),
        ),
    ]
