# Generated by Django 5.2 on 2025-05-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_quantity_name_quantityvariant_variant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='static/products'),
        ),
    ]
